### ISSUE TITLE
Server Name Idication (SNI)

### ISSUE THREAD

**Issue by vchrisb** [EMCECS/smart-client-java#2]
smart-client-java does use the [apache httpclient version 4.2.6](https://github.com/EMCECS/smart-client-java/blob/master/build.gradle#L42)
According to [HTTPCLIENT-1119](https://issues.apache.org/jira/browse/HTTPCLIENT-1119) does this client only start supporting SNI with version 4.3.2

The smart-client-java is used by ecs-object-client-java, which does not allow using SNI with the default client.

**Comment by twincitiesguy** [comment]
If SNI is a requirement for you, you should be able to override the httpclient version in your maven/gradle build, or include the newer jar file in your app (with appropriate dependencies).

We tried using a newer version of httpclient in the past, but unfortunately, Jersey 1.19 was written to leverage httpclient features which were deprecated in 4.3 and we have other customers who complain about deprecation warnings.  This puts us in a tight spot because Jersey 2 does not offer the flexibility we need, but Jersey 1 requires older libraries.
